version: "3"

services:
  api:
    image: webdevops/php-apache:alpine
    environment:
      - WEB_ALIAS_DOMAIN=api.vm # Add this to your hosts file
    ports:
      - '8080:443'
    volumes:
      - api-sync:/app
  app:
    image: webdevops/php-apache:alpine
    environment:
      - WEB_ALIAS_DOMAIN=app.vm # Add this to your hosts file
    ports:
      - '8090:443'
    volumes:
      - app-sync:/app
volumes:
  api-sync:
    external: true
  app-sync:
    external: true
